language: python

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7d967d9679efbbc43466
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20160619/texlive.tar.xz | tar -JxC $HOME/texlive

install:
# Sphinx requirements
  - pip install -r requirements.txt
# Latex requirements
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - tlmgr update --self
  - tlmgr install combelow
  - tlmgr install babel-french
  - tlmgr install babel-german
  - tlmgr install babel-romanian
  - tlmgr install babel-italian
  - tlmgr install babel-spanish

before_script:
  - ./scripts/ci/setup_git.sh
  - ./scripts/ci/transifex_push.sh

script:
  - ./scripts/build-docs.sh

after_success:
  - ./scripts/ci/deploy-docs.sh

env:
  global:
    # Transifex password
    - secure: "zBggrd/qZMP8mPj3CLbY2bsztD92p+DruyafvyoqWzlZT0uXXibYSasirkmQX+gYGr7Q6BInu3CvACYImu+UJqiAk0z+3ZZ9BYNj46VWXfkyynKxwb2MXqm8su75FLdKFPNS09OH48QMFWQLgwvMf33PvF9bmj1l8P3WKzoXBmsWaWufnCDHKME34uqkIUABwSuH26dF0ELajfK57/+UaK8NUo+9tEcw6SGcOeWjRrUMD795we/N/6akrIpqwzhn0yqXe3e3yMEO5X/pC7Fx6t+M+ug2S60xZqwyAD2ZlMwind1v9qy60hI9x6UAQT+vxY+HmvA+0okPzvi2KaFOhgumu/YPxjjITUiXqnplvp7Pp8opqJjyaFdgI2iKuYz8JyL+phoUQg2RDqerFR3Vq4Hf3qe2ZRJHW3dE4nAPbqJ6z7Nh55rsjpAUBhhO0Xkja+orcMdMs3bJb/W2f42TqFY3HNIXrTZgsKAX9WlnXjsY3FHF8yJ/0ZkGj8Na8PxUWdBafxR/cdOsXshrFFZ9eB7Kf4otYfJISsfVYRISEz2SKcNz4fq12sIPE5E9n6xk7mOTBWJN7OgN2r7i2fepGLfiEzB3r2H3/R4VpqYi+FTqOxtZyK9cayaIswpAinKW6eUXA+J0v3YRywqGZ7ZK9ntkcc1Taoo5a3PEyy9zXIU="
