language: python

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7d967d9679efbbc43466
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20160619/texlive.tar.xz | tar -JxC $HOME/texlive

install:
# Sphinx requirements
  - pip install -r requirements.txt
# Latex requirements
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - tlmgr update --self
  - tlmgr install combelow
  - tlmgr install babel-french
  - tlmgr install babel-german
  - tlmgr install babel-romanian
  - tlmgr install babel-italian
  - tlmgr install babel-spanish

before_script:
  - ./scripts/ci/setup_git.sh
  - ./scripts/ci/transifex_push.sh

script:
  - ./scripts/build-docs.sh

after_success:
  - ./scripts/ci/deploy-docs.sh

env:
  global:
    # Transifex password
    - secure: "YchIV/Tr2Ig3A7oWh3Dp5CaPBHViz7oQfQE7+6S5uKYp3d1BRmH2A7dAIWtnz2qRNBy1Yq/qUxbUeRwAfpJInWYOTfwU3U7L/DuYSQZA3uRCsyr21K5KFOiwOO25Wcbk+dV398T4F3bQGr0CudiDDxQ/+dLSgYtZXH376xWvbt5YOBU/5hoGn8b69lgD22Ty+qCV8/liYNFTUU/k1so/RXyTm1DcsEDSjBjVuO6pdX02nuyLzWChAkRZfOdYd/B9cEogof5LvR0EeBL2kHE5gjAwZKToty4PPbBK66NJocKfb3f4t1GBKSMKlPsZ+/QPavQhbX7qbNQtsH8SB4xtM8hvoFOFOvhdDpRZDejhYsVrc41hLSsU0xMWZ+l/M05Spi6kBtk4Lu0p0w/EtSkcOr02wrX5KOFOmA7ZlkqRR/ArwOG20yBhcPVIdpAM9Q9k5kPLbB37o+WbClz7+C+0A/sC5kRWBP8IxE5y4okS7UxnEmkMngDgucEbu6ksdXCccMdBccd8cOWMRVT+VHBjW0ONz9MDQTa3poXNNyn80zr7GjZyTbZG37ZqI2q7WTZjTyXSyv6ca3FGs+dCtlKH1M0p0a4qBeoaWzr/awsn7Yn2xPpqNX9lvaOUBGyW/JaGczmgLN41jm/Zwhyq2kuW9SMm6sny4XvFoZ3DnafNdro="
